import React, { useMemo, useState } from 'react';
import { ArrowRight, Brain, CheckCircle2, Clock, Cpu, FileText, GitCommit, Layers, Lock, Play, RotateCcw, ShieldAlert, ShieldCheck, XCircle } from 'lucide-react';
import type { ExecutionContext } from '../types';

interface ExecutionsViewProps {
  executions: ExecutionContext[];
  selectedExecutionId: string | null;
  onSelectExecution: (id: string) => void;
  onRunPipeline: (id: string) => Promise<void>;
  onNavigateToLedger: (eventId: string) => void;
  onReplayExecution: (id: string) => void;
}

type Filter = 'ALL' | 'COMPLETED' | 'ESCALATED' | 'DENIED' | 'PENDING';
type NodeId = 'request' | 'context' | 'agent' | 'proposal' | 'evidence' | 'policy' | 'auth' | 'exec' | 'event' | 'memory';

const tone = (s: string) => s === 'COMPLETED' || s === 'VERIFIED' || s === 'ALLOW' ? 'emerald' : s === 'DENIED' || s === 'REJECTED' || s === 'FAILED' ? 'rose' : s === 'ESCALATED' || s === 'UNCERTAIN' || s === 'ESCALATE' ? 'amber' : 'cyan';

export const ExecutionsView: React.FC<ExecutionsViewProps> = ({ executions, selectedExecutionId, onSelectExecution, onRunPipeline, onNavigateToLedger, onReplayExecution }) => {
  const [filter, setFilter] = useState<Filter>('ALL');
  const [activeNode, setActiveNode] = useState<NodeId | null>('policy');
  const selected = executions.find(e => e.executionId === selectedExecutionId) ?? executions[0] ?? null;
  const filtered = useMemo(() => executions.filter(e => filter === 'ALL' || e.status === filter), [executions, filter]);
  const nodes = useMemo(() => !selected ? [] : [
    { id:'request' as NodeId, n:'01', label:'REQUEST', state:'COMPLETED', icon:FileText, detail:selected.request.input },
    { id:'context' as NodeId, n:'02', label:'CONTEXT', state:'COMPLETED', icon:Layers, detail:`${selected.context.memoryRecords.length} memory records · ${selected.context.activeRules.length} active rules` },
    { id:'agent' as NodeId, n:'03', label:'AGENT', state:'COMPLETED', icon:Cpu, detail:`${selected.agentReasoning.specialist} · ${selected.agentId}` },
    { id:'proposal' as NodeId, n:'04', label:'PROPOSAL', state:selected.proposal ? 'COMPLETED' : 'PENDING', icon:Brain, detail:selected.proposal?.summary ?? 'Proposal not generated yet.' },
    { id:'evidence' as NodeId, n:'05', label:'EVIDENCE', state:selected.evidence.length ? 'COMPLETED' : 'PENDING', icon:ShieldCheck, detail:`${selected.evidence.length} records · ${selected.verification.confidence}% verification confidence` },
    { id:'policy' as NodeId, n:'06', label:'POLICY GATE', state:selected.policyDecision?.outcome ?? 'PENDING', icon:Lock, detail:selected.policyDecision?.reason ?? 'Awaiting deterministic policy evaluation.' },
    { id:'auth' as NodeId, n:'07', label:'AUTHORIZATION', state:selected.authorization ? (selected.authorization.authorized ? 'COMPLETED' : 'DENIED') : 'PENDING', icon:ShieldCheck, detail:selected.authorization ? `${selected.authorization.method} · ${selected.authorization.authorizer}` : 'Awaiting authorization.' },
    { id:'exec' as NodeId, n:'08', label:'EXECUTION', state:selected.status, icon:Play, detail:selected.executionResult ? `${selected.executionResult.durationMs}ms · ${selected.executionResult.sideEffects.length} side effects` : 'No execution result committed.' },
    { id:'event' as NodeId, n:'09', label:'EVENT LEDGER', state:selected.receipt ? 'COMPLETED' : 'PENDING', icon:GitCommit, detail:selected.receipt ? `Receipt ${selected.receipt.txHash}` : 'No canonical receipt yet.' },
    { id:'memory' as NodeId, n:'10', label:'MEMORY', state:selected.status === 'COMPLETED' ? 'COMPLETED' : 'PENDING', icon:Brain, detail:selected.status === 'COMPLETED' ? 'Execution state eligible for memory commit.' : 'Memory commit follows successful execution.' },
  ], [selected]);
  const active = nodes.find(n => n.id === activeNode);
  const policy = selected?.policyDecision;
  const replay = selected?.replayStatus;

  return <div className="factory-enter space-y-5 pb-12">
    <header className="factory-panel factory-grid relative overflow-hidden p-5"><div className="factory-vignette pointer-events-none absolute inset-0 opacity-60"/><div className="relative flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-2 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.22em] text-cyan-400/80"><span className="h-1.5 w-1.5 rounded-full bg-cyan-400"/>Runtime / Execution Control</div><h1 className="flex items-center gap-2 font-mono text-xl font-bold uppercase text-neutral-100"><GitCommit className="h-5 w-5 text-cyan-400"/>Execution Inspector</h1><p className="mt-1 max-w-3xl font-mono text-xs leading-relaxed text-neutral-400">Trace every transition from intent to verified state, with policy, authorization, receipt and replay state visible at the decision point.</p></div><div className="flex flex-wrap gap-1.5 rounded-lg border border-neutral-800 bg-neutral-950/80 p-1 font-mono text-[10px]">{(['ALL','COMPLETED','ESCALATED','DENIED','PENDING'] as Filter[]).map(f => <button key={f} onClick={() => setFilter(f)} className={`rounded-md px-2.5 py-1.5 ${filter===f ? 'bg-cyan-400/10 text-cyan-300 ring-1 ring-cyan-400/30' : 'text-neutral-500 hover:bg-neutral-800 hover:text-neutral-200'}`}>{f}<span className="ml-1.5 text-neutral-600">{f==='ALL'?executions.length:executions.filter(e=>e.status===f).length}</span></button>)}</div></div></header>

    <div className="grid grid-cols-1 gap-5 lg:grid-cols-12"><aside className="lg:col-span-4 xl:col-span-3"><div className="factory-panel sticky top-4 overflow-hidden"><div className="flex items-center justify-between border-b border-neutral-800 px-4 py-3"><div><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-neutral-500">Execution Queue</div><div className="font-mono text-xs font-semibold text-neutral-200">{filtered.length} traces</div></div><Clock className="h-4 w-4 text-neutral-600"/></div><div className="max-h-[760px] space-y-1.5 overflow-y-auto p-2">{filtered.map(ex => { const t=tone(ex.status); const c=t==='emerald'?'text-emerald-400 border-emerald-500/30 bg-emerald-500/5':t==='rose'?'text-rose-400 border-rose-500/30 bg-rose-500/5':t==='amber'?'text-amber-400 border-amber-500/30 bg-amber-500/5':'text-cyan-400 border-cyan-500/30 bg-cyan-500/5'; return <button key={ex.executionId} onClick={()=>onSelectExecution(ex.executionId)} className={`w-full rounded-lg border p-3 text-left ${selected?.executionId===ex.executionId?'border-cyan-400/50 bg-cyan-400/[0.06] shadow-[inset_2px_0_0_rgba(103,232,249,0.9)]':'border-neutral-800/80 bg-neutral-950/40 hover:border-neutral-700'}`}><div className="flex items-center justify-between gap-2"><span className="font-mono text-[11px] font-bold text-neutral-200">{ex.executionId}</span><span className={`rounded border px-1.5 py-0.5 font-mono text-[9px] ${c}`}>{ex.status}</span></div><p className="mt-2 line-clamp-2 text-[11px] text-neutral-300">{ex.request.input}</p><div className="mt-2 flex justify-between border-t border-neutral-900 pt-2 font-mono text-[9px] text-neutral-600"><span>{ex.agentReasoning.specialist}</span><span>{new Date(ex.timestamp).toLocaleTimeString()}</span></div></button>})}{!filtered.length&&<div className="p-6 text-center font-mono text-[10px] text-neutral-600">NO EXECUTION TRACES MATCH FILTER</div>}</div></div></aside>

    <main className="min-w-0 space-y-5 lg:col-span-8 xl:col-span-9">{selected ? <>
      <section className="factory-panel factory-grid overflow-hidden p-4"><div className="flex flex-col gap-3 border-b border-neutral-800 pb-3 md:flex-row md:items-center md:justify-between"><div><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-cyan-400/70">Active Execution Trace</div><div className="mt-1 flex items-center gap-2"><span className="font-mono text-sm font-bold text-neutral-100">{selected.executionId}</span><span className="text-neutral-700">/</span><span className="font-mono text-[10px] text-neutral-500">{selected.traceId}</span></div></div><div className="flex gap-2"><button onClick={()=>onReplayExecution(selected.executionId)} className="flex items-center gap-1.5 rounded-md border border-neutral-700 bg-neutral-900 px-2.5 py-1.5 font-mono text-[10px] text-purple-300"><RotateCcw className="h-3 w-3"/>REPLAY</button>{selected.status==='PENDING'&&<button onClick={()=>onRunPipeline(selected.executionId)} className="flex items-center gap-1.5 rounded-md border border-cyan-400/50 bg-cyan-400/10 px-2.5 py-1.5 font-mono text-[10px] font-bold text-cyan-300"><Play className="h-3 w-3 fill-current"/>RUN PIPELINE</button>}</div></div><div className="mt-4 overflow-x-auto pb-1"><div className="flex min-w-[980px] items-stretch gap-1.5">{nodes.map((node,i)=>{const Icon=node.icon;const isActive=activeNode===node.id;const t=tone(node.state);const border=t==='emerald'?'border-emerald-500/25':t==='rose'?'border-rose-500/35':t==='amber'?'border-amber-500/30':'border-cyan-500/25';return <React.Fragment key={node.id}><button onClick={()=>setActiveNode(isActive?null:node.id)} className={`relative w-[105px] shrink-0 rounded-md border p-2 text-left ${isActive?'border-cyan-400 bg-cyan-400/10 ring-1 ring-cyan-400/30':`${border} bg-neutral-950/75 hover:border-neutral-600`}`}><div className="flex justify-between"><Icon className="h-3.5 w-3.5 text-neutral-400"/><span className="font-mono text-[8px] text-neutral-600">{node.n}</span></div><div className="mt-3 truncate font-mono text-[9px] font-semibold text-neutral-200">{node.label}</div><div className="mt-1 truncate font-mono text-[8px] text-neutral-600">{node.state}</div></button>{i<nodes.length-1&&<div className="flex w-3 shrink-0 items-center justify-center text-neutral-700"><ArrowRight className="h-3 w-3"/></div>}</React.Fragment>})}</div></div>{active&&<div className="mt-3 rounded-md border border-cyan-500/20 bg-cyan-400/[0.025] p-3"><div className="flex justify-between gap-3 font-mono text-[9px] uppercase tracking-[0.16em] text-cyan-400/80"><span>Selected Stage · {active.n} / {active.label}</span><span className="text-neutral-500">{active.state}</span></div><p className="mt-2 font-mono text-[11px] leading-relaxed text-neutral-300">{active.detail}</p></div>}</section>

      <section className="grid grid-cols-2 gap-2 md:grid-cols-4">{[['STATUS',selected.status],['DOMAIN',selected.request.domain],['ACTOR',selected.actorId],['MODE',selected.mode]].map(([l,v])=><div key={l} className="factory-panel-raised p-3"><div className="font-mono text-[9px] uppercase tracking-[0.16em] text-neutral-600">{l}</div><div className="mt-1 truncate font-mono text-[11px] font-semibold text-neutral-200">{v}</div></div>)}</section>

      <section className="grid gap-4 xl:grid-cols-2"><div className="factory-panel-raised p-4"><div className="mb-3 flex items-center gap-2 border-b border-neutral-800 pb-2"><FileText className="h-4 w-4 text-cyan-400"/><h3 className="font-mono text-[11px] font-bold uppercase text-neutral-200">01 / Intent & Context</h3></div><p className="rounded-md border border-neutral-800 bg-neutral-950/80 p-3 font-mono text-xs text-neutral-200">{selected.request.input}</p><div className="mt-3 grid grid-cols-2 gap-2 font-mono text-[9px]"><div className="rounded border border-neutral-800 p-2"><span className="text-neutral-600">INTENT</span><div className="mt-1 text-neutral-300">{selected.request.intent}</div></div><div className="rounded border border-neutral-800 p-2"><span className="text-neutral-600">CAPABILITY</span><div className="mt-1 text-neutral-300">{selected.capabilityId}</div></div></div></div><div className="factory-panel-raised p-4"><div className="mb-3 flex items-center justify-between border-b border-neutral-800 pb-2"><div className="flex items-center gap-2"><Cpu className="h-4 w-4 text-purple-400"/><h3 className="font-mono text-[11px] font-bold uppercase text-neutral-200">02 / Specialist Reasoning</h3></div><span className="font-mono text-[9px] text-purple-400">{selected.agentReasoning.specialist}</span></div><div className="space-y-1.5">{selected.agentReasoning.steps.map(s=><div key={s.step} className="flex gap-2 rounded-md border border-neutral-800 bg-neutral-950/70 p-2.5"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded border border-purple-500/30 bg-purple-500/10 font-mono text-[9px] text-purple-300">{s.step}</span><span className="font-mono text-[11px] text-neutral-300">{s.thought}</span></div>)}{!selected.agentReasoning.steps.length&&<span className="font-mono text-[10px] text-neutral-600">AWAITING PIPELINE EXECUTION</span>}</div></div></section>

      <section className="grid gap-4 xl:grid-cols-2"><div className="factory-panel-raised p-4"><div className="mb-3 flex items-center justify-between border-b border-neutral-800 pb-2"><div className="flex items-center gap-2"><Lock className="h-4 w-4 text-cyan-400"/><h3 className="font-mono text-[11px] font-bold uppercase text-neutral-200">06 / Policy Gate</h3></div><span className={`font-mono text-[10px] font-bold ${policy?.outcome==='DENY'?'text-rose-400':policy?.outcome==='ESCALATE'?'text-amber-400':'text-emerald-400'}`}>{policy?.outcome??'PENDING'}</span></div><div className="grid grid-cols-2 gap-2 font-mono text-[10px]"><div className="rounded border border-neutral-800 p-2"><span className="text-neutral-600">RISK</span><div className="mt-1 text-neutral-200">{policy?.riskScore??selected.verification.riskScore}</div></div><div className="rounded border border-neutral-800 p-2"><span className="text-neutral-600">CONFIDENCE</span><div className="mt-1 text-neutral-200">{policy?.confidence??selected.verification.confidence}%</div></div></div><p className="mt-3 font-mono text-[10px] text-neutral-400">{policy?.reason??'Deterministic gate has not evaluated this execution.'}</p></div><div className="factory-panel-raised p-4"><div className="mb-3 flex items-center justify-between border-b border-neutral-800 pb-2"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-cyan-400"/><h3 className="font-mono text-[11px] font-bold uppercase text-neutral-200">07 / Authorization</h3></div><span className="font-mono text-[10px] text-neutral-400">{selected.authorization?.method??'PENDING'}</span></div>{selected.authorization?<div className="space-y-2 font-mono text-[10px]"><div className={selected.authorization.authorized?'text-emerald-400':'text-rose-400'}>{selected.authorization.authorized?<CheckCircle2 className="mr-1 inline h-3.5 w-3.5"/>:<XCircle className="mr-1 inline h-3.5 w-3.5"/>}{selected.authorization.authorized?'AUTHORIZED':'NOT AUTHORIZED'}</div><div className="text-neutral-500">AUTHORISER <span className="text-neutral-300">{selected.authorization.authorizer}</span></div></div>:<div className="font-mono text-[10px] text-neutral-600">AUTHORIZATION GATE HAS NOT BEEN REACHED</div>}</div></section>

      <section className="factory-panel-raised p-4"><div className="mb-3 flex items-center justify-between border-b border-neutral-800 pb-2"><div className="flex items-center gap-2"><GitCommit className="h-4 w-4 text-cyan-400"/><h3 className="font-mono text-[11px] font-bold uppercase text-neutral-200">09 / Canonical Receipt & Replay</h3></div>{replay?.diverged?<span className="flex items-center gap-1 font-mono text-[9px] text-rose-400"><ShieldAlert className="h-3 w-3"/>DIVERGENCE DETECTED</span>:<span className="flex items-center gap-1 font-mono text-[9px] text-emerald-400"><CheckCircle2 className="h-3 w-3"/>TRACE CONSISTENT</span>}</div>{selected.receipt?<div className="grid gap-3 md:grid-cols-3"><div className="rounded border border-neutral-800 bg-neutral-950/70 p-2.5 font-mono"><span className="text-[8px] text-neutral-600">TX HASH</span><div className="mt-1 truncate text-[10px] text-neutral-300">{selected.receipt.txHash}</div></div><div className="rounded border border-neutral-800 bg-neutral-950/70 p-2.5 font-mono"><span className="text-[8px] text-neutral-600">EVENT</span><div className="mt-1 truncate text-[10px] text-neutral-300">{selected.receipt.eventId}</div><button onClick={()=>onNavigateToLedger(selected.receipt!.eventId)} className="mt-2 text-[9px] text-cyan-400">OPEN LEDGER →</button></div><div className="rounded border border-neutral-800 bg-neutral-950/70 p-2.5 font-mono"><span className="text-[8px] text-neutral-600">DURATION</span><div className="mt-1 text-[10px] text-neutral-300">{selected.receipt.durationMs} ms</div></div></div>:<div className="rounded border border-neutral-800 bg-neutral-950/70 p-3 font-mono text-[10px] text-neutral-600">NO CANONICAL RECEIPT COMMITTED</div>}{replay?.diverged&&<div className="mt-3 rounded border border-rose-500/25 bg-rose-500/5 p-3 font-mono text-[10px] text-rose-300"><ShieldAlert className="mr-2 inline h-3.5 w-3.5"/>REPLAY DIVERGENCE: {replay.divergenceReason??'Replay state differs from original execution.'}</div>}</section>
    </> : <div className="factory-panel p-10 text-center font-mono text-xs text-neutral-600">NO EXECUTION TRACE AVAILABLE</div>}</main></div></div>;
