import React from 'react';
import {
  Settings,
  Cpu,
  Server,
  Database,
  CheckCircle2,
  Lock,
  RotateCcw,
  Sparkles,
} from 'lucide-react';
import type { SystemStatus } from '../types';

interface SettingsViewProps {
  status: SystemStatus | null;
  onRefresh: () => void;
}

export const SettingsView: React.FC<SettingsViewProps> = ({ status, onRefresh }) => {
  return (
    <div className="space-y-6 pb-12 font-mono text-xs">
      {/* Header */}
      <div className="border-b border-neutral-800 pb-4">
        <h1 className="text-lg font-bold text-neutral-100 uppercase tracking-wide flex items-center gap-2">
          <Settings className="h-5 w-5 text-cyan-400" />
          <span>Kernel Diagnostics & System Configuration</span>
        </h1>
        <p className="text-xs text-neutral-400 font-sans mt-0.5">
          Runtime parameters, cryptographic engine status, and architectural compliance diagnostics.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* System Diagnostics */}
        <div className="rounded-xl border border-neutral-800 bg-neutral-900/50 p-5 space-y-4">
          <span className="font-bold text-neutral-100 uppercase block border-b border-neutral-800 pb-2">
            Runtime Engine Health
          </span>

          <div className="space-y-2.5">
            <div className="flex items-center justify-between p-2.5 rounded bg-neutral-950 border border-neutral-800">
              <span className="text-neutral-400">Kernel Version:</span>
              <span className="text-neutral-200 font-bold">{status?.kernelVersion || 'v2.4.0-production'}</span>
            </div>

            <div className="flex items-center justify-between p-2.5 rounded bg-neutral-950 border border-neutral-800">
              <span className="text-neutral-400">SHA-256 Ledger State:</span>
              <span className="text-emerald-400 font-bold flex items-center gap-1">
                <CheckCircle2 className="h-3.5 w-3.5" />
                {status?.ledgerIntegrity || 'VERIFIED'}
              </span>
            </div>

            <div className="flex items-center justify-between p-2.5 rounded bg-neutral-950 border border-neutral-800">
              <span className="text-neutral-400">Active Runtime Mode:</span>
              <span className="text-cyan-400 font-bold">{status?.activeMode || 'LIVE'}</span>
            </div>

            <div className="flex items-center justify-between p-2.5 rounded bg-neutral-950 border border-neutral-800">
              <span className="text-neutral-400">Deterministic Policy Gate:</span>
              <span className="text-emerald-400 font-bold">ONLINE & ENFORCED</span>
            </div>
          </div>

          <button
            onClick={onRefresh}
            className="w-full py-2 rounded-lg bg-neutral-800 hover:bg-neutral-700 text-neutral-200 font-bold transition text-xs"
          >
            Re-Poll Kernel Daemon
          </button>
        </div>

        {/* Source Repository & Architectural Compliance */}
        <div className="rounded-xl border border-neutral-800 bg-neutral-900/50 p-5 space-y-4">
          <span className="font-bold text-neutral-100 uppercase block border-b border-neutral-800 pb-2">
            Architectural Specification Source
          </span>

          <div className="space-y-2 text-neutral-300 font-sans text-xs">
            <p>
              This Factory Control Plane is directly derived from the canonical systems architecture at:
            </p>
            <div className="p-2.5 rounded bg-neutral-950 border border-neutral-800 font-mono text-cyan-300 text-xs">
              github.com/Daniel550-pixel/The-Factory
            </div>
            <p className="text-neutral-400 leading-relaxed text-[11px]">
              Every execution enforces the invariant: <strong>AI DECIDES ≠ AI EXECUTES</strong>. Proposals generated by AI models are evaluated deterministically by the kernel policy engine before any state transition or side-effect is recorded onto the immutable SHA-256 event ledger.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
