import React from 'react';
import { Settings, CheckCircle2, RotateCcw } from 'lucide-react';
import type { SystemStatus } from '../types';

interface SettingsViewProps { status: SystemStatus | null; onRefresh: () => void; }

export const SettingsView: React.FC<SettingsViewProps> = ({ status, onRefresh }) => <div className="factory-enter factory-grid factory-vignette min-h-full space-y-6 pb-12 font-mono text-xs">
  <div className="factory-panel factory-scan border-x-0 border-t-0 px-1 pb-5 pt-1"><h1 className="flex items-center gap-2 text-lg font-bold uppercase tracking-wide text-neutral-100"><Settings className="h-5 w-5 text-cyan-400"/> Kernel Diagnostics & System Configuration</h1><p className="mt-1 max-w-4xl font-sans text-xs text-neutral-400">Runtime health, ledger integrity, policy enforcement, and architectural compliance state.</p></div>
  <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
    <section className="factory-panel-raised rounded-xl p-5"><div className="flex items-center justify-between border-b border-neutral-800 pb-3"><span className="font-bold uppercase text-neutral-100">Runtime Engine Health</span><span className="text-[10px] text-emerald-400">NOMINAL</span></div><div className="mt-4 space-y-2.5">
      <div className="factory-panel flex items-center justify-between rounded-lg p-3"><span className="text-neutral-500">KERNEL VERSION</span><span className="font-bold text-neutral-200">{status?.kernelVersion||'v2.4.0-production'}</span></div>
      <div className="factory-panel flex items-center justify-between rounded-lg p-3"><span className="text-neutral-500">SHA-256 LEDGER</span><span className="flex items-center gap-1.5 font-bold text-emerald-400"><CheckCircle2 className="h-3.5 w-3.5"/>{status?.ledgerIntegrity||'VERIFIED'}</span></div>
      <div className="factory-panel flex items-center justify-between rounded-lg p-3"><span className="text-neutral-500">ACTIVE RUNTIME MODE</span><span className="font-bold text-cyan-400">{status?.activeMode||'LIVE'}</span></div>
      <div className="factory-panel flex items-center justify-between rounded-lg p-3"><span className="text-neutral-500">POLICY GATE</span><span className="font-bold text-emerald-400">ONLINE / ENFORCED</span></div>
    </div><button onClick={onRefresh} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg border border-neutral-700 bg-neutral-900 py-2.5 font-bold text-neutral-200 transition hover:border-cyan-500/40 hover:bg-neutral-800"><RotateCcw className="h-3.5 w-3.5"/> Re-Poll Kernel Daemon</button></section>
    <section className="factory-panel-raised rounded-xl p-5"><div className="flex items-center justify-between border-b border-neutral-800 pb-3"><span className="font-bold uppercase text-neutral-100">Architectural Compliance</span><span className="text-[10px] text-cyan-400">CANONICAL</span></div><div className="mt-4 space-y-3"><div className="factory-panel rounded-lg p-3"><span className="block text-[10px] uppercase text-neutral-500">Specification Source</span><span className="mt-1 block break-all text-cyan-300">github.com/Daniel550-pixel/The-Factory-2.0</span></div><div className="rounded-lg border border-cyan-900/60 bg-cyan-950/15 p-4"><span className="block text-[10px] font-bold uppercase text-cyan-300">Kernel Invariant</span><span className="mt-2 block text-sm font-bold text-neutral-100">AI DECIDES ≠ AI EXECUTES</span><p className="mt-2 font-sans text-[11px] leading-relaxed text-neutral-400">AI proposals remain subject to deterministic policy evaluation before state transitions or side-effects are admitted to the canonical ledger.</p></div><div className="grid grid-cols-2 gap-2"><div className="factory-panel rounded p-3"><span className="block text-[10px] text-neutral-500">LEDGER MODEL</span><span className="text-neutral-200">IMMUTABLE / HASHED</span></div><div className="factory-panel rounded p-3"><span className="block text-[10px] text-neutral-500">AUTHORIZATION</span><span className="text-neutral-200">POLICY-GATED</span></div></div></div></section>
  </div>
</div>;
