import React, { useState } from 'react';
import { FlaskConical, Play } from 'lucide-react';
import type { Agent } from '../types';

interface SimulationViewProps { agents: Agent[]; onRunSimulation: (scenario: { title:string; agentId:string; domain:string; hypothesis:string; variables:Record<string,any> }) => Promise<any>; }

export const SimulationView: React.FC<SimulationViewProps> = ({ agents, onRunSimulation }) => {
  const [selectedAgentId,setSelectedAgentId]=useState(agents[0]?.id||'agent-infra-ops');
  const [title,setTitle]=useState('UAE Grid Extreme Heat Wave Load Balancing (50°C)');
  const [hypothesis,setHypothesis]=useState('Evaluate if pre-cooling thermal storage can avert peak power blackouts when ambient temp reaches 50°C.');
  const [ambientTemp,setAmbientTemp]=useState(50); const [tariffMultiplier,setTariffMultiplier]=useState(1.4); const [isSimulating,setIsSimulating]=useState(false); const [simResult,setSimResult]=useState<any|null>(null);
  const handleSimulate=async(e:React.FormEvent)=>{e.preventDefault();setIsSimulating(true);try{const selectedAgent=agents.find(a=>a.id===selectedAgentId);setSimResult(await onRunSimulation({title,agentId:selectedAgentId,domain:selectedAgent?.type||'INFRASTRUCTURE_OPS',hypothesis,variables:{ambientTemp,tariffMultiplier}}));}finally{setIsSimulating(false);}};
  return <div className="factory-enter factory-grid factory-vignette min-h-full space-y-6 pb-12">
    <div className="factory-panel factory-scan border-x-0 border-t-0 px-1 pb-5 pt-1"><h1 className="flex items-center gap-2 font-mono text-lg font-bold uppercase tracking-wide text-neutral-100"><FlaskConical className="h-5 w-5 text-amber-400"/> Counterfactual Simulation Sandbox</h1><p className="mt-1 max-w-4xl font-mono text-xs text-neutral-400">Run isolated counterfactuals with explicit variables, specialist attribution, and a hard separation from the canonical execution ledger.</p></div>
    <div className="grid grid-cols-1 gap-5 lg:grid-cols-12">
      <div className="lg:col-span-6"><div className="factory-panel-raised rounded-xl p-5 font-mono text-xs"><div className="flex items-center justify-between border-b border-neutral-800 pb-3"><span className="font-bold uppercase text-neutral-100">Scenario Parameters</span><span className="rounded border border-amber-500/30 bg-amber-500/10 px-2 py-1 text-[10px] text-amber-300">ISOLATED SANDBOX</span></div><form onSubmit={handleSimulate} className="mt-4 space-y-3">
        <label className="block"><span className="mb-1 block text-[10px] uppercase text-neutral-500">Scenario Title</span><input value={title} onChange={e=>setTitle(e.target.value)} required className="w-full rounded border border-neutral-800 bg-neutral-950 px-3 py-2 text-xs text-neutral-200 focus:border-amber-500/50 focus:outline-none"/></label>
        <label className="block"><span className="mb-1 block text-[10px] uppercase text-neutral-500">Simulation Specialist</span><select value={selectedAgentId} onChange={e=>setSelectedAgentId(e.target.value)} className="w-full rounded border border-neutral-800 bg-neutral-950 px-3 py-2 text-xs text-neutral-200 focus:border-amber-500/50 focus:outline-none">{agents.map(ag=><option key={ag.id} value={ag.id}>{ag.name} ({ag.type})</option>)}</select></label>
        <label className="block"><span className="mb-1 block text-[10px] uppercase text-neutral-500">Simulation Hypothesis</span><textarea rows={3} value={hypothesis} onChange={e=>setHypothesis(e.target.value)} required className="w-full resize-none rounded border border-neutral-800 bg-neutral-950 p-2.5 text-xs text-neutral-200 focus:border-amber-500/50 focus:outline-none"/></label>
        <div className="grid grid-cols-2 gap-3 pt-1"><label><span className="mb-2 block text-[10px] uppercase text-neutral-500">Ambient Temp <b className="text-amber-300">{ambientTemp}°C</b></span><input type="range" min={30} max={55} value={ambientTemp} onChange={e=>setAmbientTemp(Number(e.target.value))} className="w-full accent-amber-400"/></label><label><span className="mb-2 block text-[10px] uppercase text-neutral-500">Tariff <b className="text-amber-300">{tariffMultiplier}x</b></span><input type="range" min={1} max={2.5} step={0.1} value={tariffMultiplier} onChange={e=>setTariffMultiplier(Number(e.target.value))} className="w-full accent-amber-400"/></label></div>
        <button type="submit" disabled={isSimulating} className="mt-2 flex w-full items-center justify-center gap-2 rounded-lg bg-amber-500 py-2.5 font-bold text-neutral-950 transition hover:bg-amber-400 disabled:opacity-60"><Play className="h-3.5 w-3.5 fill-current"/>{isSimulating?'Computing Simulation...':'Run Isolated Simulation'}</button>
      </form></div></div>
      <div className="lg:col-span-6"><div className="factory-panel-raised rounded-xl p-5 font-mono text-xs"><div className="flex items-center justify-between border-b border-neutral-800 pb-3"><span className="font-bold uppercase text-neutral-100">Simulation Forecast & Results</span><span className="text-[10px] text-neutral-500">NO LIVE SIDE-EFFECTS</span></div>{simResult?<div className="mt-4 space-y-3"><div className="factory-panel rounded-lg p-3.5"><span className="block text-[10px] font-bold uppercase text-amber-300">Forecast Outcome Summary</span><p className="mt-2 font-sans text-xs leading-relaxed text-neutral-200">{simResult.summary||`At ${ambientTemp}°C ambient heat and ${tariffMultiplier}x tariff multiplier, pre-cooling reduces total substation peak surge by 34.2 MW, avoiding rolling brownouts across 18 industrial plots with an estimated cost saving of $184,000 USD.`}</p></div><div className="grid grid-cols-2 gap-2"><div className="factory-panel rounded p-3"><span className="block text-[10px] text-neutral-500">PEAK LOAD SHAVED</span><span className="font-bold text-emerald-400">34.2 MW (-24%)</span></div><div className="factory-panel rounded p-3"><span className="block text-[10px] text-neutral-500">THERMAL RELIABILITY</span><span className="font-bold text-emerald-400">99.8% NOMINAL</span></div></div><div className="rounded-lg border border-amber-900/60 bg-amber-950/20 p-3 text-[11px] text-amber-300"><span className="font-bold">EPISTEMIC NOTE:</span><p className="mt-1">Synthetic counterfactual only. No live state or canonical ledger mutation occurred.</p></div></div>:<div className="flex min-h-64 items-center justify-center p-8 text-center text-neutral-500">Configure parameters and run the isolated simulation to generate a counterfactual impact model.</div>}</div></div>
    </div>
  </div>;
};
